spring:
  application:
    name: spring1
  
  # Настройки источника данных (DataSource)
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # Настройки JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Настройки Hibernate
    hibernate:
      ddl-auto: validate
  
  # Настройки Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

resilience4j:
  circuitbreaker:
    instances:
      backendACircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      combinedCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  
  ratelimiter:
    instances:
      basicRateLimiter:
        registerHealthIndicator: true
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
      customRateLimiter:
        registerHealthIndicator: true
        limitForPeriod: 2
        limitRefreshPeriod: 20s
        timeoutDuration: 3s
      combinedRateLimiter:
        registerHealthIndicator: true
        limitForPeriod: 3
        limitRefreshPeriod: 15s
        timeoutDuration: 5s

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents,ratelimiters,ratelimiterevents
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true 

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 